### ISSUE TITLE
word_list.txt

### ISSUE THREAD

**Issue by ElijahSink** [frostming/wordle-tg#1]
Could I ask where you got your word list, or would you mind attaching it here?

**Comment by frostming** [comment]
The game is purely client-side. The word list is retrieved with some reverse engineering. Knowing the word list will ruin your game experience so I attach it in this repo encoded. If you are curious about it you can find a way to decode it in the source code.

**Comment by frostming** [comment]
Oh, I thought it was `wordle-tui`, for this repo, the word list is from https://gist.github.com/laixintao/96559596a4e1108d4ce2a412e801b2cf
